---
- name: Установка и настройка LightHouse
  hosts: all
  become: true
  tasks:
    - name: Скачивание статики LightHouse
      ansible.builtin.get_url:
        url: https://github.com/GoogleChrome/lighthouse/archive/refs/heads/main.zip
        dest: /tmp/lighthouse.zip
        mode: '0644'  # Установка правильных прав доступа

    - name: Распаковка статики LightHouse
      ansible.builtin.unarchive:
        src: /tmp/lighthouse.zip
        dest: /var/www/lighthouse
        remote_src: true

    - name: Установка Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Настройка конфигурации Nginx для LightHouse
      ansible.builtin.template:
        src: lighthouse_nginx.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: '0644'  # Установка правильных прав доступа
      notify:
        - Перезапуск Nginx

    - name: Запуск Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Перезапуск Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
