---
- name: Install Clickhouse
  hosts: clickhouse
  become: yes

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove old ClickHouse packages
      ansible.builtin.apt:
        name: clickhouse-common-static
        state: absent

    - name: Create directory for Clickhouse client
      ansible.builtin.file:
        path: /tmp/clickhouse-common-static
        state: directory
        mode: '0755'  # Опционально, чтобы устанавливать права доступа

    - name: Get Clickhouse common static distribution
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_22.3.3.44_amd64.deb"
        dest: "/tmp/clickhouse-common-static/clickhouse-common-static_22.3.3.44_amd64.deb"

    - name: Install Clickhouse common static
      ansible.builtin.apt:
        deb: "/tmp/clickhouse-common-static/clickhouse-common-static_22.3.3.44_amd64.deb"
